Smooth Audio Playback
kixelated/moq-js pull request #110
Opened 2024-07-31 18:54 UTC by kelvinkirima014

This PR is a first attempt at fixing #3. It introduces smooth audio playback using a single channel, i.e mono audio. Future work should extend this functionality to support stereo audio.

2024-07-31 23:06 UTC, kixelated requested changes
I don't understand the changes to the ring buffer. Does mono audio work without these those changes?

2024-07-31 23:06 UTC, kixelated commented on lib/common/ring.ts
> +		 const numberOfSamples = frame.numberOfFrames * samplesPerFrame
Multiplying by 1 for mono audio if I'm not mistaken? Same as the previous code?

2024-07-31 23:06 UTC, kixelated commented on lib/common/ring.ts
> +		samplesPerFrame = frame.numberOfChannels
The poor naming is partly my fault. AudioData uses `frame == sample` while I use `frames == group of samples`.

2024-08-01 11:34 UTC, kelvinkirima014 commented on lib/common/ring.ts
> +		samplesPerFrame = frame.numberOfChannels
Reverted to using the previous code as it works with mono audio and is a bit more dynamic with the channel count.

2024-11-09 04:46 UTC, closed without merging